# Generated by Django 5.2.14 on 2026-05-11 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('estacion', 'Estación de Trabajo'), ('lavacabeza', 'Lava-Cabezas')], max_length=20, verbose_name='tipo')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta (si aplica)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock actual')),
                ('stock_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('porcentaje_comision', models.IntegerField(default=35, help_text='Porcentaje de comisión para el profesional (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje de comisión')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_contratacion', models.DateField(auto_now_add=True, verbose_name='fecha de contratación')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio_sugerido', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio sugerido')),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración estimada del servicio en minutos', verbose_name='duración estimada (minutos)')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('descripcion', models.TextField(help_text='Nombre o descripción del tratamiento/fórmula', verbose_name='descripción')),
                ('formula_quimica', models.TextField(help_text='Proporciones, marcas, colores, tiempos de acción, etc.', verbose_name='fórmula química')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='gestion.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.profesional', verbose_name='profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'Habilidad del Profesional',
                'verbose_name_plural': 'Habilidades de los Profesionales',
            },
        ),
        migrations.AddField(
            model_name='profesional',
            name='habilidades',
            field=models.ManyToManyField(related_name='profesionales', through='gestion.HabilidadProfesional', through_fields=('profesional', 'servicio'), to='gestion.servicio', verbose_name='habilidades'),
        ),
        migrations.CreateModel(
            name='DetalleTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_real', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio real')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'Detalle del Turno',
                'verbose_name_plural': 'Detalles de los Turnos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='gestion.cliente', verbose_name='cliente')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='gestion.estacion', verbose_name='estación')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='gestion.profesional', verbose_name='profesional')),
                ('servicios', models.ManyToManyField(related_name='turnos', through='gestion.DetalleTurno', through_fields=('turno', 'servicio'), to='gestion.servicio', verbose_name='servicios')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.turno', verbose_name='turno'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'Mercado Pago')], max_length=20, verbose_name='método de pago')),
                ('comision', models.DecimalField(decimal_places=2, help_text='Comisión ya calculada: total × (profesional.porcentaje_comision / 100)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='comisión')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='gestion.turno', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.AddConstraint(
            model_name='habilidadprofesional',
            constraint=models.UniqueConstraint(fields=('profesional', 'servicio'), name='uq_habilidad_profesional'),
        ),
        migrations.AddConstraint(
            model_name='detalleturno',
            constraint=models.UniqueConstraint(fields=('turno', 'servicio'), name='uq_detalle_turno'),
        ),
    ]
