# Generated by Django 5.2.14 on 2026-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='día de la semana')),
                ('hora_apertura', models.TimeField(verbose_name='hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='hora de cierre')),
                ('abierto', models.BooleanField(default=True, verbose_name='abierto')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_fin_estimada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de fin estimada'),
        ),
    ]
