# Generated by Django 5.2.14 on 2026-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_horarioatencion_turno_hora_fin_estimada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Nombre o descripción del tratamiento/fórmula', null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='formula_quimica',
            field=models.TextField(blank=True, help_text='Proporciones, marcas, colores, tiempos de acción, etc.', null=True, verbose_name='fórmula química'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
    ]
