# Generated by Django 5.2.14 on 2026-05-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_fichatecnica_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Turno en el que se generó esta ficha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_tecnicas', to='gestion.turno', verbose_name='turno asociado'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='observaciones'),
            preserve_default=False,
        ),
    ]
