# Generated by Django 5.2.14 on 2026-05-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_fichatecnica_turno_alter_fichatecnica_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
