# Generated by Django 5.2.14 on 2026-05-13 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_profesional_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_insumo',
            field=models.BooleanField(default=False, verbose_name='¿Es insumo interno (ej. coloración)?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_para_venta',
            field=models.BooleanField(default=True, verbose_name='¿Es para la venta al público?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('gramos', 'Gramos'), ('mililitros', 'Mililitros')], default='unidades', max_length=20, verbose_name='unidad de medida'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='gestion.cliente', verbose_name='cliente (si es venta libre)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta al público (si aplica)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='gestion.turno', verbose_name='turno'),
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(help_text='En la unidad de medida del producto (ej. 45 gramos)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad usada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consumos', to='gestion.producto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='gestion.turno')),
            ],
            options={
                'verbose_name': 'Consumo de Insumo',
                'verbose_name_plural': 'Consumos de Insumos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='gestion.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='gestion.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta de Producto',
                'verbose_name_plural': 'Detalles de Venta de Productos',
            },
        ),
    ]
