# Generated by Django 5.2.14 on 2026-05-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_producto_es_insumo_producto_es_para_venta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['orden_sugerido', 'nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden_sugerido',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden predefinido de la peluquería para secuencias de servicios (menor = primero)', verbose_name='orden sugerido'),
        ),
        migrations.AddField(
            model_name='turno',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posición del turno dentro de la secuencia de la reserva', verbose_name='orden en la reserva'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_reserva', to='gestion.reserva', verbose_name='reserva asociada'),
        ),
    ]
