# Generated by Django 5.2.14 on 2026-05-14 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_reserva_compuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoinsumo',
            name='cantidad_usada',
            field=models.DecimalField(decimal_places=2, help_text='En la unidad de medida del producto (ej. 45.50 gramos)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='cantidad usada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock mínimo'),
        ),
    ]
