# Generated by Django 5.2.14 on 2026-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_consumoinsumo_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreExcepcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='motivo/descripción')),
                ('es_dia_completo', models.BooleanField(default=True, verbose_name='todo el día')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='hora fin')),
            ],
            options={
                'verbose_name': 'Cierre Excepcional',
                'verbose_name_plural': 'Cierres Excepcionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'ordering': ['dia_semana', 'hora_apertura'], 'verbose_name': 'Horario de Atención', 'verbose_name_plural': 'Horarios de Atención'},
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana'),
        ),
    ]
