# Generated by Django 5.2.14 on 2026-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_cierreexcepcional_alter_horarioatencion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('por_reprogramar', 'Por Reprogramar')], default='pendiente', max_length=20, verbose_name='estado'),
        ),
    ]
