# Generated by Django 5.2.14 on 2026-05-21 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='token único'),
        ),
    ]
