# Generated by Django 5.2.14 on 2026-05-21 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_reserva_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token único'),
        ),
    ]
