# Generated by Django 5.2.14 on 2026-05-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_reserva_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_estimada',
        ),
        migrations.CreateModel(
            name='EtapaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Ej: 1 (Primero), 2 (Segundo)', verbose_name='orden de ejecución')),
                ('nombre', models.CharField(help_text='Ej: Aplicación, Exposición, Lavado', max_length=100, verbose_name='nombre de la etapa')),
                ('duracion', models.PositiveIntegerField(help_text='Debe ser múltiplo de 5 para encajar en el motor de slots.', verbose_name='duración (minutos)')),
                ('tipo_estacion', models.CharField(choices=[('estacion', 'Estación de Trabajo (Silla)'), ('lavacabeza', 'Lavacabezas'), ('ninguna', 'Ninguna / Sala de Espera')], max_length=20, verbose_name='estación requerida')),
                ('requiere_profesional', models.BooleanField(default=True, help_text='Desmarcar si es un tiempo de espera (ej: esperando que actúe la tintura) donde el profesional se libera.', verbose_name='¿Requiere al profesional?')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='gestion.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Etapa de Servicio',
                'verbose_name_plural': 'Etapas de Servicio',
                'ordering': ['orden'],
                'unique_together': {('servicio', 'orden')},
            },
        ),
    ]
