# Generated by Django 5.2.14 on 2026-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_remove_servicio_duracion_estimada_etapaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (opcional para extranjeros)', max_length=15, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad', max_length=15, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
