# Generated by Django 5.2.14 on 2026-05-29 00:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_cliente_dni_profesional_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleturno',
            name='estacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estacion', verbose_name='estación'),
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de fin'),
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de inicio'),
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.profesional', verbose_name='profesional'),
        ),
        migrations.AddField(
            model_name='turno',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='token de autogestión'),
        ),
        migrations.CreateModel(
            name='ComisionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('detalle_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion.detalleturno', verbose_name='detalle del turno')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.profesional', verbose_name='profesional')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'Comisión por Detalle',
                'verbose_name_plural': 'Comisiones por Detalle',
            },
        ),
    ]
