# Generated by Django 5.2.14 on 2026-05-29 00:52

from django.db import migrations, models
import uuid


def poblar_detalle_turno(apps, schema_editor):
    DetalleTurno = apps.get_model('gestion', 'DetalleTurno')
    for dt in DetalleTurno.objects.select_related('turno').iterator():
        dt.profesional = dt.turno.profesional
        dt.estacion = dt.turno.estacion
        if dt.turno.fecha_hora:
            dt.hora_inicio = dt.turno.fecha_hora.time()
        if dt.turno.hora_fin_estimada:
            dt.hora_fin = dt.turno.hora_fin_estimada.time()
        dt.save(update_fields=['profesional', 'estacion', 'hora_inicio', 'hora_fin'])


def poblar_tokens(apps, schema_editor):
    Turno = apps.get_model('gestion', 'Turno')
    # Some rows may share the same UUID (Django calls default once when
    # adding field to existing rows on SQLite). Regenerate ALL tokens
    # unconditionally so the subsequent unique constraint succeeds.
    batch = []
    for turno in Turno.objects.iterator():
        turno.token = uuid.uuid4()
        batch.append(turno)
        if len(batch) >= 500:
            Turno.objects.bulk_update(batch, ['token'])
            batch = []
    if batch:
        Turno.objects.bulk_update(batch, ['token'])


def migrar_observaciones(apps, schema_editor):
    Turno = apps.get_model('gestion', 'Turno')
    for turno in Turno.objects.filter(reserva__isnull=False).select_related('reserva').iterator():
        if turno.reserva.observaciones and turno.orden == 0:
            obs = turno.observaciones or ''
            turno.observaciones = f"{obs}\n[Reserva: {turno.reserva.observaciones}]".strip()
            turno.save(update_fields=['observaciones'])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_detalleturno_estacion_detalleturno_hora_fin_and_more'),
    ]

    operations = [
        migrations.RunPython(poblar_detalle_turno),
        migrations.RunPython(poblar_tokens),
        migrations.RunPython(migrar_observaciones),
        migrations.AlterField(
            model_name='turno',
            name='token',
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, editable=False,
                null=True, verbose_name='token de autogestión'
            ),
        ),
    ]
