# Generated by Django 5.2.14 on 2026-05-29 01:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_poblar_detalle_turno_y_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='profesional',
        ),
        migrations.AlterField(
            model_name='detalleturno',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.estacion', verbose_name='estación'),
        ),
        migrations.AlterField(
            model_name='detalleturno',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.profesional', verbose_name='profesional'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token de autogestión'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
