# Generated by Django 5.2.14 on 2026-05-29 02:26

import django.db.models.deletion
from datetime import time as time_type
from django.db import migrations, models


def backfill_detalle_etapa(apps, schema_editor):
    """Crea DetalleEtapa para cada DetalleTurno existente.

    Para servicios con múltiples etapas, la primera etapa recibe la estación
    almacenada y las etapas subsiguientes reciben estacion=None.
    Los horarios se distribuyen proporcionalmente según la duración de cada etapa.
    """
    DetalleTurno = apps.get_model('gestion', 'DetalleTurno')
    DetalleEtapa = apps.get_model('gestion', 'DetalleEtapa')
    EtapaServicio = apps.get_model('gestion', 'EtapaServicio')

    for dt in DetalleTurno.objects.select_related('servicio').iterator():
        etapas = list(EtapaServicio.objects.filter(
            servicio=dt.servicio_id
        ).order_by('orden'))

        if not etapas:
            continue

        total_duracion = sum(e.duracion for e in etapas)

        if dt.hora_inicio and dt.hora_fin and total_duracion > 0:
            base_min = dt.hora_inicio.hour * 60 + dt.hora_inicio.minute
            fin_min = dt.hora_fin.hour * 60 + dt.hora_fin.minute
            total_minutos = fin_min - base_min
        else:
            total_minutos = 0

        cumulative = 0
        for i, etapa in enumerate(etapas):
            if total_minutos > 0:
                offset_start = int(total_minutos * cumulative / total_duracion)
                offset_end = int(total_minutos * (cumulative + etapa.duracion) / total_duracion)
                h_ini = time_type((base_min + offset_start) // 60, (base_min + offset_start) % 60)
                h_fin = time_type((base_min + offset_end) // 60, (base_min + offset_end) % 60)
            else:
                h_ini = dt.hora_inicio
                h_fin = dt.hora_fin

            # Solo la primera etapa hereda la estación del DetalleTurno
            estacion_id = dt.estacion_id if i == 0 else None

            DetalleEtapa.objects.create(
                detalle=dt,
                etapa_servicio=etapa,
                estacion_id=estacion_id,
                hora_inicio=h_ini,
                hora_fin=h_fin,
            )
            cumulative += etapa.duracion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_remove_turno_reserva_remove_turno_estacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_asignadas', to='gestion.detalleturno', verbose_name='detalle del turno')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estacion', verbose_name='estación asignada')),
                ('etapa_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.etapaservicio', verbose_name='etapa del servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Etapa',
                'verbose_name_plural': 'Detalles de Etapas',
                'indexes': [models.Index(fields=['estacion'], name='gestion_det_estacio_43a799_idx')],
                'constraints': [models.UniqueConstraint(fields=('detalle', 'etapa_servicio'), name='uq_detalle_etapa')],
            },
        ),
        migrations.RunPython(backfill_detalle_etapa, migrations.RunPython.noop),
    ]
