# Generated by Django 5.2.14 on 2026-05-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_detalle_etapa_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleturno',
            name='estacion',
        ),
    ]
