# Generated by Django 5.2.14 on 2026-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_remove_detalleturno_estacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleetapa',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de fin'),
        ),
        migrations.AlterField(
            model_name='detalleetapa',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de inicio'),
        ),
        migrations.AlterField(
            model_name='detalleturno',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de fin'),
        ),
        migrations.AlterField(
            model_name='detalleturno',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de inicio'),
        ),
    ]
