# Generated by Django 5.2.14 on 2026-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_alter_detalleetapa_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='tipo',
            field=models.CharField(choices=[('estacion', 'Estación de Trabajo'), ('lavacabeza', 'Lava-Cabezas'), ('manicura', 'Puesto de Manicura')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='etapaservicio',
            name='tipo_estacion',
            field=models.CharField(choices=[('estacion', 'Estación de Trabajo (Silla)'), ('lavacabeza', 'Lavacabezas'), ('manicura', 'Puesto de Manicura'), ('ninguna', 'Ninguna / Sala de Espera')], max_length=20, verbose_name='estación requerida'),
        ),
    ]
