# Generated by Django 5.2.14 on 2026-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_estacion_tipo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comisiondetalle',
            constraint=models.UniqueConstraint(fields=('venta', 'detalle_turno'), name='uq_comision_venta_detalle'),
        ),
        migrations.AddConstraint(
            model_name='consumoinsumo',
            constraint=models.UniqueConstraint(fields=('turno', 'producto'), name='uq_consumo_turno_producto'),
        ),
        migrations.AddConstraint(
            model_name='detalleventaproducto',
            constraint=models.UniqueConstraint(fields=('venta', 'producto'), name='uq_detalle_venta_producto'),
        ),
    ]
